### ISSUE TITLE
NumericField Trunc-ing

### ISSUE THREAD

**Issue by JeffCFinn** [majkel89/dbase#11]
Was trunc-ing all numbers.
I changed (int) to (float) on lines 31 and 38 /field/NumericField.php.

**Comment by majkel89** [comment]
- Numeric fields holds only integer values. If you would like to return value in particular way use filter instead of modifying code base https://github.com/majkel89/dbase#filters
- Number is truncated to the length of the field.

**Comment by emielmolenaar** [comment]
Do filters have precedence over the truncated value of the field? For example, will a (for example) FloatingPointFilter do the trick to store floats in numeric fields?

**Comment by majkel89** [comment]
Apparently no (https://github.com/majkel89/dbase/blob/master/src/field/NumericField.php#L38).

I missed the fact that Numeric field can store floating point numbers (http://www.oocities.org/geoff_wass/dBASE/GaryWhite/dBASE/FAQ/qformt.htm).

The solution to your problem would be to drop casting to integer and truncating ;-)
Casting to floating point number could in some edge cases result in loosing precision.

I would be glad if you push PR for this.

**Comment by emielmolenaar** [comment]
Well, I have been using a fork of your library for a few months now (https://github.com/emielmolenaar/dbase/commit/4a3285f55d82dadf3311ed1eaa008411020bb3a5) . It's working fine, but I have no idea if such a PR would break stuff for others (I guess so :smile: ). We might just have to check the type of the incoming value and return the same type of value.

**Comment by DBLaci** [comment]
The issue seems to be solved in a fork in this commit: https://github.com/naril/dbase/commit/0c8828dbc374cb4ae1e1881229f69bde825a5ef5

(the fix in the previous comment only fixes the truncate on reading)

**Comment by emielmolenaar** [comment]
Sweet! Indeed my "fix" was just a simple hacky one to quick fix truncating. @majkel89 Would you accept a PR that merges https://github.com/naril/dbase/commit/0c8828dbc374cb4ae1e1881229f69bde825a5ef5 into this library?

**Comment by majkel89** [comment]
@emielmolenaar could you verify that this version works for you `org.majkel/dbase:dev-decimal-fixes`

**Comment by emielmolenaar** [comment]
I will verify this, but I have to do that in collaboration with a client of mine. Will report back here.

**Comment by majkel89** [comment]
@emielmolenaar Did you verified the package (`org.majkel/dbase:dev-decimal-fixes`) that it works with decimal numbers.

If you are unable to do so please provide me sample data.

**Comment by emielmolenaar** [comment]
@majkel89 Excuse me for the delay, but `org.majkel/dbase:dev-decimal-fixes` seems to work correctly for me!

**Comment by majkel89** [comment]
fixed i 1.1.6

**Comment by richarls** [comment]
I get 1.1.7 version and I have this problem, I tried to insert a float number with point and comma, but It will save integer in both times.
I see the value of this field before save the record and It has 2 decimals, but the value is integer in dbf.
