### ISSUE TITLE
out of memory when opening the following dbf + fpt

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [majkel89/dbase#13]
https://drive.google.com/drive/folders/1eXFITzn1qIHJJGPm-M0QYdZgl8o9vS5f?usp=sharing

**Comment by majkel89** [comment]
What version of php are you using (`php -i`) ?

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
7.0.something...

**Comment by majkel89** [comment]
I'm currently investigating the problem. I found that for FoxPro memo fields are stored as 32 bit integer instead of 10 characters long number. But I still cannot generate out of memory error.

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
Hey!

Here's my version of PHP

http://prntscr.com/kp05pp

**Comment by majkel89** [comment]
please verify if this verion of the package fixes the issue `composer require org.majkel/dbase:dev-issue-13`.

Requires `"minimum-stability": "dev"` in your `composer.json`

**Comment by majkel89** [comment]
I'm closing the issue due to lack of response.
