### ISSUE TITLE
a problem?

### ISSUE THREAD

**Issue by netmou** [majkel89/dbase#6]
※ErrorMessage: Format `dBASE III PLUS` does not support field ``
※ErrorFile: vendor\org.majkel\dbase\src\Format.php
※ErrorLine: 486
※ErrorTrace: 
--#1 org\majkel\dbase\Format->createField() On line 459 In file "vendor\org.majkel\dbase\src\Format.php"
---- With the args in json format: [{"n":"","t":"\u0000","rr1":0,"ll":0,"dd":0,"rr2":0,"wa":0,"rr3":0,"sff":0,"rr4":0}]
--#2 org\majkel\dbase\Format->readHeader() On line 66 In file "vendor\org.majkel\dbase\src\Format.php"
---- With the args in json format: []
--#3 org\majkel\dbase\Format->getHeader() On line 75 In file "vendor\org.majkel\dbase\src\Format.php"
---- With the args in json format: []
--#4 org\majkel\dbase\Format->isValid() On line 99 In file "vendor\org.majkel\dbase\src\FormatFactory.php"
---- With the args in json format: []
--#5 call_user_func() On line 43 In file "vendor\org.majkel\dbase\src\FormatFactory.php"
---- With the args in json format: [{},"all1.dbf","rb"]
--#6 org\majkel\dbase\FormatFactory->getFormat() On line 61 In file "vendor\org.majkel\dbase\src\Table.php"
---- With the args in json format: ["auto","all1.dbf","rb"]
--#7 org\majkel\dbase\Table::fromFile() On line 10 In file "maincnt\zhaosheng\luqu-import.php"
---- With the args in json format: ["all1.dbf"]

**Comment by majkel89** [comment]
most likely. could you give me the file that causes it ?

**Comment by netmou** [comment]
a specific file created by foxpro6.0:
[bbb.zip](https://github.com/majkel89/dbase/files/481415/bbb.zip)
casue the  problem;
other dbf files , created by  libreoffice calc, have no problem

**Comment by majkel89** [comment]
fixed in v1.1.1
