### ISSUE TITLE
Parse error: syntax error, unexpected 'use' (T_USE) 

### ISSUE THREAD

**Issue by CCH4GITHUB** [majkel89/dbase#7]
Hi
require_once 'vendor/autoload.php'
use org.majkel\dbase\src\Table;
$dbf = Table::fromFile('EMPLOYEE.DBF');
( ! ) Parse error: syntax error, unexpected 'use' (T_USE) in C:\wamp64\www\yii2-basic\testdbf.php on line 4

How to fix the parsing error from Eclipse PDT

**Comment by majkel89** [comment]
````
require_once 'vendor/autoload.php'      // <---- missing semicolon [;]
use org.majkel\dbase\src\Table;
$dbf = Table::fromFile('EMPLOYEE.DBF');
````

**Comment by CCH4GITHUB** [comment]
Warning: require_once(C:\wamp64\www\yii2-basic\yii2-basic\vendor\composer/autoload_real.php): failed to open stream: No such file or directory in C:\wamp64\www\yii2-basic\vendor\autoload.php on line 7


Call Stack


#

Time

Memory

Function

Location

1 0.0007 248856 {main}( ) ...\testdbf.php:0 
2 0.0012 251872 require_once( 'C:\wamp64\www\yii2-basic\vendor\autoload.php' ) ...\testdbf.php:2 
 


( ! ) Fatal error: require_once(): Failed opening required 'C:\wamp64\www\yii2-basic\yii2-basic\vendor\composer/autoload_real.php' (include_path='.;C:\php\pear') in C:\wamp64\www\yii2-basic\vendor\autoload.php on line 7


Call Stack


#

Time

Memory

Function

Location

1 0.0007 248856 {main}( ) ...\testdbf.php:0 
2 0.0012 251872 require_once( 'C:\wamp64\www\yii2-basic\vendor\autoload.php' ) ...\testdbf.php:2

**Comment by majkel89** [comment]
it seems project dependencies are missing. Run `composer install -o` to install them
